on: [push]

jobs:
  rpm_build:
    runs-on: ubuntu-latest
    name: A job to test rpm build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: test rpm package build
      id: rpm
      uses: osallou/rpmchecker-action@master
    - name: get rpmversion
      run: echo "Rpm package version ${{steps.rpm.outputs.rpmversion}}"
